# Generated by Django 5.2.6 on 2025-09-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_clinic_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_start', models.CharField(max_length=20)),
                ('slot_duration', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=20)),
                ('created_by', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.slot')),
            ],
        ),
    ]
