# Generated by Django 5.2.6 on 2025-09-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.slot'),
        ),
    ]
