# Generated by Django 5.2.6 on 2025-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_clinic_user_alter_patient_user_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_user',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
