# Generated by Django 5.2.6 on 2025-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_clinic_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
