# Generated by Django 5.2.6 on 2025-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_clinic_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic_user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='clinic_user',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
