# Generated by Django 5.2.6 on 2025-09-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('patients', '0005_remove_clinic_user_date_joined_and_more'), ('patients', '0006_remove_clinic_user_is_active'), ('patients', '0007_clinic_user_date_joined_clinic_user_is_logged_in'), ('patients', '0008_alter_clinic_user_date_joined'), ('patients', '0009_clinic_user_request_count')]

    dependencies = [
        ('patients', '0004_clinic_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic_user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='clinic_user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='clinic_user',
            name='is_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='clinic_user',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic_user',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
