# Generated by Django 5.2.6 on 2025-09-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_clinic_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic_user',
            name='is_active',
        ),
    ]
