# Generated by Django 5.2.6 on 2025-09-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_clinic_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_user',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinic_user',
            name='is_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
