# Generated by Django 5.2.6 on 2025-09-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_clinic_user_date_joined_clinic_user_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_user',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
