# Generated by Django 5.2.6 on 2025-09-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_clinic_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_user',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
